### ISSUE TITLE
404 page not showing

### ISSUE THREAD

**Issue by LeulAria** [zemachfm/zemachfm-frontend#47]
![sss](https://user-images.githubusercontent.com/45531307/121075579-083fd400-c7de-11eb-9952-0a716bf0e07a.png)

**Comment by henoktsegaye** [comment]
@LeulAria  Thanks for that issue, that issue is related with 404 netlify and 404 next. we need to configure netlify for this. we need a PR for this.

**Comment by LeulAria** [comment]
may be
/* /index.html 200       in _redirects

**Comment by abdulhamidOumer** [comment]
@LeulAria We've actually tried this. This would have worked when next doesn't have the locale functionality turned on. But in our case Next genertes an `en.html` and `am.html` files. So we had to write a rule like this based on the locale `/am/* /am.html 200` . But for some reason this won't work for three level subpages like `/am/hosts/something`. Only solution that came to mind was to make other ridirect rules for each of this routes. But that seemed unscalable. So we just kept it this way till we find a better way but if nothing works we are gonna have to use that.

**Comment by henoktsegaye** [comment]
so @abdulhamidOumer  stated , there is an issue with the amharic characters being on the url, there were the same issue with axios , that has to be encoded before sending.

**Comment by abdulhamidOumer** [comment]
@henoktsegaye that's true, have also found this [open issue](https://answers.netlify.com/t/paths-with-accents-not-found-and-cause-redirect/27417/30) on the netlify forum . So we can either try writing the encoded URI rule on the redirect directly for the Amharic hosts or find another way to retrieve them from the backend, for the next episode release maybe.

**Comment by abdulhamidOumer** [comment]
This is fixed now
